### ISSUE TITLE
Exception Ljava/lang/UnsatisfiedLinkError; thrown while initializing Lorg/go3k/ccxwebview/CCXWebview;

### ISSUE THREAD

**Issue by lajiang** [go3k/CCXWebview#2]
W/dalvikvm(624): Exception Ljava/lang/UnsatisfiedLinkError; thrown while initializing Lorg/go3k/ccxwebview/CCXWebview;
W/dalvikvm(624): Class init failed in newInstance call (Lorg/go3k/ccxwebview/CCXWebview;)

**Comment by kicpang** [comment]
Have you set up the Cocos2D-X library for CCXWebview?

**Comment by go3k** [comment]
Sorry, I don't concern this repo for a long time...
I decide to upgrade this repo, and try my best to simplify the usage of this module.
- support both cocos2dx v2.x and v3.x
- just copy and past to use it.

**Comment by cbryeon** [comment]
THANK
